org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true

neogradle.subsystems.conventions.runs.create-default-run-per-type=false

project_type=LIBRARY

lib.group=com.github.minecraftschurlimods
lib.name=betterhudlib
lib.version=1.0
lib.vendor=Minecraftschurli

java_version=21

github.owner=MinecraftschurliMods
github.repo=BetterHUDLib

license.name=MIT
license.url=https://opensource.org/licenses/MIT
license.file=LICENSE

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28

mc_version=1.21
neo_version=21.0.148
